#!/bin/bash

# 🔧 Fix Array Jobs and Resubmit Script
# Cancels current broken jobs and resubmits with fixed particle list logic

echo "🔧 FIXING ARRAY JOBS"
echo "===================="

echo "📋 Current job status (before fixes):"
echo "❌ Jobs 5064866, 5064867, 5026590 are using incorrect file discovery mode"
echo "❌ They're looking for invalid PIDs (718, 800, 852) in wrong H5 files"
echo ""

echo "✅ FIXED ISSUES:"
echo "1. Updated brute_force_gpu_job.sh to use particle_list.txt"
echo "2. Changed array size to 1-22713 (total particles)"
echo "3. Fixed PID lookup to use array index instead of hardcoded PIDs"
echo ""

echo "🚀 TO RESUBMIT CORRECTLY:"
echo "========================="
echo ""
echo "1. Cancel current broken jobs:"
echo "   scancel 5064866 5064867 5026590"
echo ""
echo "2. Upload fixed scripts to Sherlock:"
echo "   ./rsync_to_sherlock.sh"
echo ""
echo "3. Submit using SMART GPU submission (RECOMMENDED):"
echo ""
echo "   # Option A: Smart submission (filters completed, chunks automatically)"
echo "   ./submit_gpu_smart.sh"
echo ""
echo "   # Option B: Manual chunked submission"
echo "   ./submit_gpu_chunked.sh --chunk-size 200 --concurrent 3"
echo ""
echo "   # Option C: Test with small chunk first"
echo "   ./submit_gpu_chunked.sh --chunk-size 50 --concurrent 2 --dry-run"
echo ""
echo "⚠️  DO NOT use the direct sbatch command anymore - it will hit QOS limits!"
echo ""

echo "🎯 WHAT THE FIXED SCRIPT WILL DO:"
echo "================================="
echo "✅ Read particle_list.txt line by line"
echo "✅ Array task 1 → processes line 1 (PID 1, Halo268)"
echo "✅ Array task 39 → processes line 39 (PID 39, Halo268)"
echo "✅ Array task 40 → processes line 40 (PID 40, Halo268)"
echo "✅ Correctly match PIDs to their actual H5 files"
echo "✅ Skip already completed particles"
echo "✅ Use Kroupa IMF for all training"
echo ""

echo "🔍 VERIFICATION:"
echo "================"
echo "After resubmitting, the logs should show:"
echo "  '📋 Using particle list: particle_list.txt'"
echo "  '🎯 Processing: PID 39 from eden_scaled_Halo268...'"
echo "  'Objects: 8156 (Small)'"
echo ""
echo "Instead of the previous error:"
echo "  '⚠️  No particles found for PID 852'"
echo ""

echo "💡 TIP: Use 'squeue --me' to monitor the new jobs"
echo "💡 Use './download_sherlock_logs.sh' to check progress"
